"use client";
import React, { useState } from "react";
import { HoveredLink, Menu, MenuItem, ProductItem } from "@/components/ui/navbar-menu";
import { cn } from "@/lib/utils";
import { useUser, UserButton } from "@clerk/nextjs";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function Navbar({ className }) {
  const [active, setActive] = useState(null);
  const { user, isSignedIn } = useUser();

  return (
    <div
      className={cn("fixed top-10 inset-x-0 max-w-2xl mx-auto z-50 px-4 sm:px-0", className)}
    >
      <Menu setActive={setActive}>
        <MenuItem setActive={setActive} active={active} item="Learning">
          <div className="flex flex-col space-y-4 text-sm">
            <HoveredLink href="#features">AI Course Generation</HoveredLink>
            <HoveredLink href="#features">Smart Chapter Notes</HoveredLink>
            <HoveredLink href="#features">Personalized Study Paths</HoveredLink>
            <HoveredLink href="#features">Interactive Q&A</HoveredLink>
          </div>
        </MenuItem>
        
        <MenuItem setActive={setActive} active={active} item="Services">
          <div className="text-sm grid grid-cols-2 gap-10 p-4">
            <ProductItem
              title="Course Creator"
              href="/create"
              src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=3540&auto=format&fit=crop"
              description="Transform any topic into a complete structured course."
            />
            <ProductItem
              title="Smart Notes"
              href="/dashboard"
              src="https://images.unsplash.com/photo-1454165833267-024522856403?q=80&w=3540&auto=format&fit=crop"
              description="AI-generated summaries and deep-dives for every concept."
            />
            <ProductItem
              title="Veda Dashboard"
              href="/dashboard"
              src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=3540&auto=format&fit=crop"
              description="Centralized command center for your entire learning journey."
            />
            <ProductItem
              title="AI Study Plans"
              href="/dashboard"
              src="https://images.unsplash.com/photo-1484417856242-41109b7c8f00?q=80&w=3540&auto=format&fit=crop"
              description="Achieve your goals with custom timelines generated by Veda AI."
            />
          </div>
        </MenuItem>

        <MenuItem setActive={setActive} active={active} item="Pricing">
          <div className="flex flex-col space-y-4 text-sm">
            <HoveredLink href="#pricing">Hobby (Free)</HoveredLink>
            <HoveredLink href="#pricing">Pro Plan</HoveredLink>
            <HoveredLink href="#pricing">Enterprise</HoveredLink>
          </div>
        </MenuItem>

        <div className="flex items-center gap-4 ml-2 border-l pl-4 dark:border-white/20">
            {isSignedIn ? (
                <div className="flex items-center gap-2">
                     <Link href="/dashboard" className="text-sm font-medium hover:opacity-80 transition-opacity whitespace-nowrap">
                        Dashboard
                    </Link>
                    <UserButton afterSignOutUrl="/" />
                </div>
            ) : (
                <Link href="/sign-in" className="text-sm font-medium hover:opacity-80 transition-opacity whitespace-nowrap">
                    Sign In
                </Link>
            )}
        </div>
      </Menu>
    </div>
  );
}
